// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvH4gkHnBG171aCliK-mkcFrigf8INZEU',
    appId: '1:264217805842:web:582b92a679db306cf0c4cb',
    messagingSenderId: '264217805842',
    projectId: 'delivery-food-8a78a',
    authDomain: 'delivery-food-8a78a.firebaseapp.com',
    storageBucket: 'delivery-food-8a78a.appspot.com',
    measurementId: 'G-ELZ1W2FCKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg26PWsjnOX5C1CGX8WqNFbwNfA5OLn80',
    appId: '1:264217805842:android:ae6599b2a99287cbf0c4cb',
    messagingSenderId: '264217805842',
    projectId: 'delivery-food-8a78a',
    storageBucket: 'delivery-food-8a78a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOdoA50CpC6M3hb3U0rCSV07jVsbbE_qE',
    appId: '1:264217805842:ios:28874768add484a0f0c4cb',
    messagingSenderId: '264217805842',
    projectId: 'delivery-food-8a78a',
    storageBucket: 'delivery-food-8a78a.appspot.com',
    iosClientId: '264217805842-f5f22ogqcr89kqt0rqccjlu1qkuslgle.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryFood',
  );
}
