// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTvyX834dennWgyvA8y1HlIWPENACxUdA',
    appId: '1:709510310677:web:a8f3eb9a590b1d8342971c',
    messagingSenderId: '709510310677',
    projectId: 'delivery-food-90b04',
    authDomain: 'delivery-food-90b04.firebaseapp.com',
    storageBucket: 'delivery-food-90b04.appspot.com',
    measurementId: 'G-YJZNR1SX5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5WqkQ0QJfvwOI7Sv7ECLdQycXMHUY2Q',
    appId: '1:709510310677:android:bbd543bde6ebaaa342971c',
    messagingSenderId: '709510310677',
    projectId: 'delivery-food-90b04',
    storageBucket: 'delivery-food-90b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkb1wv4gX-uqw15mKKaOaS2JM3OT_jhWc',
    appId: '1:709510310677:ios:23bd09679297353342971c',
    messagingSenderId: '709510310677',
    projectId: 'delivery-food-90b04',
    storageBucket: 'delivery-food-90b04.appspot.com',
    iosClientId: '709510310677-g33p8i2pnli2ueg8kc68j1stlcrallgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkb1wv4gX-uqw15mKKaOaS2JM3OT_jhWc',
    appId: '1:709510310677:ios:23bd09679297353342971c',
    messagingSenderId: '709510310677',
    projectId: 'delivery-food-90b04',
    storageBucket: 'delivery-food-90b04.appspot.com',
    iosClientId: '709510310677-g33p8i2pnli2ueg8kc68j1stlcrallgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryFood',
  );
}
